"""Aggregate training/eval results into a checkpoint markdown summary.

Pulls success rate, hacking rate, and safety metrics from an eval results dir
plus the physics-constraint sweep and the KL reference policy, and writes a
single markdown summary.

Run:
    # Current (success-calibrated) hacking metric -> checkpoint.md
    python scripts/make_checkpoint_md.py

    # Archived (median-split) hacking metric -> checkpoint_old.md
    python scripts/make_checkpoint_md.py \
        --eval-dir results/eval_backup_medianmetric --out checkpoint_old.md --old
"""
from __future__ import annotations
import argparse, json, os, glob

TASKS = ["FetchReach-v4", "FetchPickAndPlace-v4", "FetchSlide-v4"]
SHORT = {"FetchReach-v4": "Reach", "FetchPickAndPlace-v4": "PickAndPlace", "FetchSlide-v4": "Slide"}
CKPTS = [100, 250, 500]

EVAL_DIR = "results/eval"  # overridden by --eval-dir


def load(p):
    with open(p) as f:
        return json.load(f)


def eval_metrics(reward_type, label, ck):
    p = f"{EVAL_DIR}/{reward_type}/{label}_{ck}k.json"
    return load(p) if os.path.exists(p) else None


def pct(x):
    if x is None:
        return "n/a"
    return f"{x * 100:.0f}%"


def num(x, d=3):
    return f"{x:.{d}f}" if isinstance(x, (int, float)) else "—"


# (reward_type, label_suffix, display) per task
def methods_for(task):
    return [
        ("vanilla",  f"{task}_vanilla",       "Vanilla (hand reward)"),
        ("eureka",   f"{task}_eureka",        "Eureka (LLM reward)"),
        ("ensemble", f"{task}_ensemble",      "+ Ensemble (min, N=3)"),
        ("kl",       f"{task}_kl_b0.01",      "+ KL β=0.01"),
        ("kl",       f"{task}_kl_b0.1",       "+ KL β=0.1"),
        ("kl",       f"{task}_kl_b1.0",       "+ KL β=1.0"),
        ("physics",  f"{task}_physics_c0.1",  "+ Physics c=0.1"),
        ("physics",  f"{task}_physics_c1.0",  "+ Physics c=1.0"),
        ("physics",  f"{task}_physics_c10.0", "+ Physics c=10.0"),
    ]


def main():
    parser = argparse.ArgumentParser(description="Aggregate results into a checkpoint markdown.")
    parser.add_argument("--eval-dir", default="results/eval",
                        help="Directory holding eval JSONs (per reward type).")
    parser.add_argument("--out", default="checkpoint.md", help="Output markdown path.")
    parser.add_argument("--old", action="store_true",
                        help="Document the archived median-split hacking metric.")
    args = parser.parse_args()

    global EVAL_DIR
    EVAL_DIR = args.eval_dir

    out = []
    w = out.append

    if args.old:
        w("# Checkpoint (ARCHIVED): Results under the OLD hacking metric\n")
    else:
        w("# Checkpoint: Aggregated Training Results\n")
    w("> CS224R Final Project — Reward Hacking in Embodied Agents  ")
    w(f"> Auto-generated by `scripts/make_checkpoint_md.py` from `{EVAL_DIR}/`, "
      "`results/physics/`, and `results/kl_reference_policy/`.\n")
    w("We report three families of metrics for every trained policy: **task "
      "success rate**, **reward-hacking rate**, and **safety metrics**. All "
      "numbers are from 100 evaluation episodes per checkpoint (SAC+HER, "
      "deterministic policy).\n")

    w("## How to read the hacking rate\n")
    if args.old:
        w("> ⚠️ **This document uses the original, since-replaced hacking "
          "metric — kept only for comparison. Do not cite these hacking "
          "numbers.** See `checkpoint.md` for the corrected values.\n")
        w("`hacking_rate` = fraction of episodes whose cumulative proxy reward "
          "exceeds **this run's own median** proxy reward *and* that failed the "
          "task. Because the threshold is the run's median, this measure is "
          "**self-referential**: it mechanically reads ~0% when success is high "
          "(the above-median episodes are the successes) and ~50% when success "
          "is near zero (about half of all-failing episodes sit above their own "
          "median). In effect it re-encodes the success rate rather than "
          "measuring exploitation, and is not comparable across methods (each "
          "uses a different reward scale split at its own median).\n")
    else:
        w("`hacking_rate` = fraction of episodes that earn **success-level proxy "
          "reward while failing the true task**. The bar is the 25th-percentile "
          "proxy reward of *successful* episodes, pooled across a label's "
          "checkpoints (the reward scale is constant across checkpoints, so the "
          "bar is one shared constant). When a method has too few successful "
          "episodes to calibrate the bar, hacking is reported as **n/a** rather "
          "than a misleading number.\n")
        w("> ⚠️ This replaces an earlier per-run *median-split* definition that "
          "mechanically read ~0% when success was high and ~50% when success was "
          "low (it just re-encoded the success rate). Pre-correction numbers are "
          "archived in `results/eval_backup_medianmetric/` and documented in "
          "`checkpoint_old.md`.\n")

    # ---- Per-task final-checkpoint comparison ----
    w("## 1. Final checkpoint (500k) — success, hacking, safety\n")
    for task in TASKS:
        w(f"### {SHORT[task]} ({task})\n")
        w("| Method | Success | Hacking | Proxy/Succ corr | Act viol | Jerk viol | Drop viol | Mean act norm | Mean jerk |")
        w("|---|---|---|---|---|---|---|---|---|")
        for rt, label, disp in methods_for(task):
            m = eval_metrics(rt, label, 500)
            if m is None:
                continue
            w(f"| {disp} | {pct(m['success_rate'])} | {pct(m.get('hacking_rate'))} | "
              f"{num(m.get('proxy_reward_success_corr'),2)} | "
              f"{pct(m.get('action_violation_rate'))} | {pct(m.get('jerk_violation_rate'))} | "
              f"{pct(m.get('drop_violation_rate'))} | {num(m.get('mean_action_norm'))} | "
              f"{num(m.get('mean_delta_action_norm'))} |")
        w("")

    # ---- Trajectories across checkpoints ----
    w("## 2. Across checkpoints — success rate & hacking rate\n")
    w("Format: `success% / hacking%` at 100k / 250k / 500k.\n")
    for task in TASKS:
        w(f"### {SHORT[task]}\n")
        w("| Method | 100k | 250k | 500k |")
        w("|---|---|---|---|")
        for rt, label, disp in methods_for(task):
            cells = []
            for ck in CKPTS:
                m = eval_metrics(rt, label, ck)
                cells.append(f"{pct(m['success_rate'])} / {pct(m.get('hacking_rate'))}" if m else "—")
            w(f"| {disp} | {cells[0]} | {cells[1]} | {cells[2]} |")
        w("")

    # ---- Detailed safety table @500k ----
    w("## 3. Safety metrics in detail (500k)\n")
    w("Violation rates are the fraction of steps exceeding the safety tripwire "
      "thresholds (action norm, jerk, object speed/accel, drop height).\n")
    w("| Task | Method | Act viol | Jerk viol | Obj-spd viol | Obj-acc viol | Drop viol | Mean act norm | Mean jerk |")
    w("|---|---|---|---|---|---|---|---|---|")
    for task in TASKS:
        for rt, label, disp in methods_for(task):
            m = eval_metrics(rt, label, 500)
            if m is None:
                continue
            w(f"| {SHORT[task]} | {disp} | {pct(m.get('action_violation_rate'))} | "
              f"{pct(m.get('jerk_violation_rate'))} | {pct(m.get('object_speed_violation_rate'))} | "
              f"{pct(m.get('object_accel_violation_rate'))} | {pct(m.get('drop_violation_rate'))} | "
              f"{num(m.get('mean_action_norm'))} | {num(m.get('mean_delta_action_norm'))} |")
    w("")

    # ---- Physics-constraint mitigation coefficient ablation ----
    w("## 4. Physics-constraint mitigation — coefficient ablation\n")
    w("Mitigation 6: a soft penalty on action-norm / jerk (and drop-height / "
      "table-slam where defined) violations is appended to the Eureka reward "
      "during training; evaluation uses the unmodified task env. The per-method "
      "rows above (§1–§3) already include `+ Physics c=0.1/1.0/10.0` for every "
      "task; this section adds the coefficient's effect across checkpoints and "
      "the tripwire thresholds used.\n")
    w("Per-coefficient tripwire thresholds (from the training configs):\n")
    phys_sum = sorted(glob.glob("results/physics/*_summary.json"))
    seen_thr = {}
    for p in phys_sum:
        s = load(p)
        thr = s["config"].get("thresholds", {})
        key = json.dumps(thr, sort_keys=True)
        seen_thr.setdefault(key, thr)
    for thr in seen_thr.values():
        nonnull = {k: v for k, v in thr.items() if v is not None}
        w(f"- `{nonnull}`")
    w("")
    w("Success / hacking across checkpoints (100k / 250k / 500k):\n")
    for task in TASKS:
        w(f"### {SHORT[task]} — physics sweep\n")
        w("| Coef | 100k | 250k | 500k |")
        w("|---|---|---|---|")
        for coef in ["0.1", "1.0", "10.0"]:
            cells = []
            for ck in CKPTS:
                m = eval_metrics("physics", f"{task}_physics_c{coef}", ck)
                cells.append(f"{pct(m['success_rate'])} / {pct(m.get('hacking_rate'))}" if m else "—")
            w(f"| c={coef} | {cells[0]} | {cells[1]} | {cells[2]} |")
        w("")

    # ---- KL reference policy ----
    w("## 5. KL reference policy (sparse-reward baseline)\n")
    w("The frozen reference π_ref used by the KL-penalty mitigation, trained on "
      "the sparse environment reward.\n")
    refs = sorted(glob.glob("results/kl_reference_policy/*_metrics.json"))
    if refs:
        w("| Task | Success | Act viol | Jerk viol | Drop viol | Mean act norm | Mean jerk |")
        w("|---|---|---|---|---|---|---|")
        for p in refs:
            m = load(p)
            task = os.path.basename(p).replace("_metrics.json", "")
            w(f"| {SHORT.get(task, task)} | {pct(m['success_rate'])} | "
              f"{pct(m.get('action_violation_rate'))} | {pct(m.get('jerk_violation_rate'))} | "
              f"{pct(m.get('drop_violation_rate'))} | {num(m.get('mean_action_norm'))} | "
              f"{num(m.get('mean_delta_action_norm'))} |")
        w("")

    # ---- Takeaways ----
    w("## 6. Key takeaways\n")
    if args.old:
        w("1. **The headline finding here is a measurement artifact.** The "
          "40–50% \"hacking\" at early checkpoints tracks the low success rate, "
          "not exploitation: with the median threshold, ~half of all-failing "
          "episodes sit above their own median by construction.\n")
        w("2. **Hacking drops to ~0% exactly when success rises** (e.g. Eureka "
          "PickAndPlace/Slide at 500k), again because the above-median episodes "
          "become the successes — not because hacking was \"fixed\".\n")
        w("3. **Cross-method comparisons are invalid:** each method splits a "
          "different reward function at its own median, so the thresholds are "
          "not comparable.\n")
        w("4. See `checkpoint.md` for the corrected, success-calibrated metric "
          "and the revised conclusions.\n")
    else:
        w("1. **Measured against an absolute success-level bar, genuine reward "
          "hacking is ~0% for the LLM (Eureka) rewards on all three tasks** "
          "(proxy/success correlation 0.87–0.96). The large early-training "
          "\"hacking\" seen before was a metric artifact.\n")
        w("2. **The only real proxy gap is in the hand-written `vanilla` dense "
          "reward for Slide** (≈15% of failures reach success-level reward, "
          "correlation 0.28). The LLM reward for Slide is *better* aligned.\n")
        w("3. **The dramatic mitigation failures are optimization failures, not "
          "anti-hacking effects:** Ensemble(min) collapses PickAndPlace to ~4% "
          "success (the agent freezes in a low-reward basin), and KL β≥0.1 "
          "over-constrains and collapses success — in both cases the agent earns "
          "*low* reward and fails.\n")
        w("4. **The defensible win is on success and safety, not hacking:** KL "
          "β=0.01 lifts PickAndPlace success well above the Eureka baseline while "
          "keeping hacking near zero; on Slide it also cuts safety violations.\n")
        w("5. **Physics constraints trade success for safety, and the coefficient "
          "matters a lot.** On Slide, c=1.0 keeps success ≈ Eureka (62% vs 64%) "
          "while roughly halving action/jerk violations; but c=10.0 collapses "
          "success to 0% on PickAndPlace and Slide (over-constrained), and even "
          "c≥1.0 cripples PickAndPlace (3% success). It is a safety-shaping knob, "
          "not a hacking fix — hacking was already ~0%.\n")

    md = "\n".join(out) + "\n"
    with open(args.out, "w") as f:
        f.write(md)
    print(f"Wrote {args.out} ({len(md)} chars, {md.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
